// <auto-generated />
using System;
using System.Collections.Generic;
using MeetupWebApi.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeetupWebApi.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221214180728_AddMeetupTableToDb")]
    partial class AddMeetupTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeetupWebApi.DAL.Models.Meetup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Schedule")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Speakers")
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("Spending")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("Sponsors")
                        .HasColumnType("text[]");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Meetups");
                });
#pragma warning restore 612, 618
        }
    }
}
